### ISSUE TITLE
Port useful changes from foolip/mdn-bcd-collector

### ISSUE THREAD

**Issue by foolip** [GooborgStudios/mdn-bcd-collector#231]
I can't submit a PR because this repo isn't recognized as a fork. But I've prepared a commit that you can easily apply:

https://github.com/foolip/mdn-bcd-collector/commit/0541cab28e0a0f66af0dc5c9c7816b4a1926382f

**Comment by queengooborg** [comment]
I've run through the commit and implemented the changes I think are useful.
