### ISSUE TITLE
Async(Generator)(Function) test seems wrong

### ISSUE THREAD

**Issue by Elchi3** [GooborgStudios/mdn-bcd-collector#254]
(I'd like to fix this but I'm still trying to understand how everything works)

So the collector proposes changes:

> javascript.builtins.AsyncFunction:
>  → support.chrome.version_added is edited ("55" → false)
>  → support.chrome_android is edited ({"version_added":"55"} → {"version_added":false}) - No longer mirrors
>  → support.edge.version_added is edited ("15" → false)
>  → support.firefox.version_added is edited ("52" → false)
>  → support.firefox_android is edited ({"version_added":"52"} → {"version_added":false}) - No longer mirrors
>  → support.opera_android is edited ({"version_added":"42"} → {"version_added":false}) - No longer mirrors
>  → support.safari.version_added is edited ("10.1" → false)
>  → support.safari_ios is edited ({"version_added":"10.3"} → {"version_added":false}) - No longer mirrors
>  → support.samsunginternet_android is edited ({"version_added":"6.0"} → {"version_added":false}) - No longer mirrors
>  → support.webview_android is edited ({"version_added":"55"} → {"version_added":false}) - No longer mirrors

I think that makes no sense. Async functions are in browsers.

https://mdn-bcd-collector.gooborg.com/tests/javascript/builtins/AsyncFunction says the test is this:
`var instance = new AsyncFunction(return true);`

[MDN says](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction): 

> Note that AsyncFunction is not a global object.

So I believe this test is wrong. I found this file https://github.com/GooborgStudios/mdn-bcd-collector/blob/0e69b4a623a6524fec62c309c9435a0241713296/custom-js.json#L64-L65

So I guess that needs changing? 
Maybe the test could be `async function a(){ return true }; a() instanceof Promise` ? Not as ctor_args, though.

**Comment by queengooborg** [comment]
I've just pushed 00908dbb314625facefacfd4185e4075171015c1 to fix `AsyncFunction`, but I'm not yet sure how to handle `AsyncGenerator` and `AsyncGeneratorFunction`.  Additionally, it seems that the `"code"` property isn't quite as robust as the custom tests are when it comes to generating subtests.

I'll leave this open as a reminder to work on `AsyncGenerator*`, and will work on moving the custom test code into `custom-tests.yaml`!
