### ISSUE TITLE
More JS tests

### ISSUE THREAD

**Issue by gsnedders** [GooborgStudios/mdn-bcd-collector#269]
if we look at bugs/PRs filed against bcd for Safari 16.4, we see: https://github.com/mdn/browser-compat-data/issues?q=%2216.4%22

if we look at this, just about the biggest category here is JS, and at least in principle many of these could be tested automatically

**Comment by queengooborg** [comment]
In dd2ee46dfb8776d1118627534aed9bb183780025, I added the data from https://github.com/jc-verse/mdn-checker/tree/master/packages/es-scraper to generate more JavaScript tests based on the specification, so I believe this issue can now be closed as completed!
